### ISSUE TITLE
Cross domain errors

### ISSUE THREAD

**Issue by pwalsh** [okfn/crowdsourced-surveys#15] opened 2018-01-31 11:34 UTC
See screenshot.

<img width="1680" alt="screenshot 2018-01-31 13 33 33" src="https://user-images.githubusercontent.com/791678/35620943-6804f702-068b-11e8-902b-9755959380a7.png">

**Comment by nightsh** [comment] 2018-01-31 11:45
@pwalsh I cannot reproduce this on latest chromium or firefox. Are you sure this is not related to browser addons? It's probably related to `postMessage` being used in the iframe source, but `targetOrigin` is set to `'*'`, which should disable checks. I will, however, try to define it explicitly and see if it goes away. What's your environment for reproducing it?

**Comment by pwalsh** [comment] 2018-01-31 11:50
@nightsh you are right, it seems to be the DuckDuckGo extension and its privacy features - it is the only extension I have. I'm running latest Safari on macOS High Sierra. Disabling DDG, I see:

<img width="1680" alt="screenshot 2018-01-31 13 49 13" src="https://user-images.githubusercontent.com/791678/35621621-acc117fc-068d-11e8-85d4-ed49f6d03bb4.png">

**Comment by nightsh** [comment] 2018-01-31 11:52
That's a bunch of errors generated by our missing transifex access rights to fetch the translations. I can handle the rejection client side, but since it doesn't block anything, I left it for after everything else is done.

**Comment by nightsh** [comment] 2018-01-31 12:06
Will close this, feel free to reopen if needed.

**Closed by nightsh** 2018-01-31 12:06 UTC
Labels: bug
